name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub에서 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # EC2에 SSH로 연결하여 Docker 이미지 Pull 및 실행
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |   
            # Docker 서비스 시작
            sudo systemctl start docker

            # 기존 컨테이너 중지 및 삭제
            docker stop sunchoii/neo || true
            docker rm sunchoii/neo || true

            # 최신 Docker 이미지 Pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/neo:latest

            # 새로운 컨테이너 실행
            docker run -d -p 80:8080 --name sunchoii/neo ${{ secrets.DOCKERHUB_USERNAME }}/neo:latest
