name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub에서 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # EC2에 SSH로 연결하여 Docker 이미지 Pull 및 실행
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Docker가 설치되어 있지 않다면 설치 (한 번만 필요)
            sudo apt update
            sudo apt install -y docker.io
            
            # Docker 서비스 시작
            sudo systemctl start docker

            # 기존 컨테이너 중지 및 삭제
            docker stop my-app || true
            docker rm my-app || true

            # 최신 Docker 이미지 Pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

            # 새로운 컨테이너 실행
            docker run -d -p 80:8080 --name my-app ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
